apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: client-port
    port: 80
    protocol: TCP
  selector:
    component: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    component: nginx
spec:
  replicas: 1
  selector:
    component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: server
          protocol: TCP
      restartPolicy: Always
